export const defaultEquivalences: { adTitle: string; propertyId: string }[] = [
  { adTitle: "Wake Up to Stunning Ocean Views â€“ Luxury Condo", propertyId: "Hyde 1905" },
  { adTitle: "Luxury Beachfront Condo in Hollywood", propertyId: "Hyde 1905" },
  { adTitle: "Stunning 2/2 Condo w Ocean View at Hyde Beach", propertyId: "Hyde 1905" },
  { adTitle: "Stunning 2/2 condo w Ocean View to Hyde Beach", propertyId: "Hyde 1905" },
  { adTitle: "Wake Up to Stunning Ocean Views – Luxury Condo", propertyId: "Hyde 1905" },
  { adTitle: "Near Miami Stadium | Spacious 2BR | Sea Views", propertyId: "Hyde 1905" },
  { adTitle: "4111 S Ocean Dr, Hollywood, FL 33019, USA", propertyId: "Hyde 1905" },
  { adTitle: "Modern Wynwood Condo W Free Parking!", propertyId: "Emilia 301" },
  { adTitle: "Wynwood Amazing Condo Sleeps 6 Close to Beach", propertyId: "Emilia 301" },
  { adTitle: "Top Location Wynwood w/ Free Parking", propertyId: "Emilia 301" },
  { adTitle: "Modern Condo Near Wynwood & Biscayne Bay!", propertyId: "Emilia 301" },
  { adTitle: "Modern Condo + Free Parking Near Wynwood", propertyId: "Emilia 301" },
  { adTitle: "Free Parking | Prime Location Near Wynwood", propertyId: "Emilia 301" },
  { adTitle: "Prime Miami Retreat | Free Parking Near Wynwood", propertyId: "Emilia 301" },
  { adTitle: "Wynwood Brand New Following CLEANING Guidelines", propertyId: "Emilia 401" },
  { adTitle: "Wynwood 2/2 Condo w Free Parking Close to Beach", propertyId: "Emilia 401" },
  { adTitle: "Miami Condo with Bay Views, Close to Downtown", propertyId: "Emilia 401" },
  { adTitle: "Condo Sleeps 5 Close to Beach", propertyId: "Emilia 401" },
  { adTitle: "Live The Perfect Vacations in Our Condo!", propertyId: "Emilia 401" },
  { adTitle: "Free Parking | Spacious Condo | Prime Location", propertyId: "Emilia 401" },
  { adTitle: "Spacious 2 Bedroom Miami Condo | Free Parking", propertyId: "Emilia 401" },
  { adTitle: "Free Parking! Modern Condo in Wynwood", propertyId: "Emilia 502" },
  { adTitle: "Wynwood 1/1 Condo w Free Parking 10 minute to Sobe", propertyId: "Emilia 502" },
  { adTitle: "Free Parking | Near to Wynwood & Design District", propertyId: "Emilia 502" },
  { adTitle: "Free Parking - Near to Wynwood & Design District", propertyId: "Emilia 502" },
  { adTitle: "Panoramic City Views: 45th Floor Brickell Condo", propertyId: "Icon 4506" },
  { adTitle: "Luxury 45th Floor Condo @ Icon Brickell", propertyId: "Icon 4506" },
  { adTitle: "Brickell Condo w/ Skyline Views", propertyId: "Icon 4506" },
  { adTitle: "Luxe 1BR Brickell • Pool • Walk to World Cup Fest", propertyId: "Icon 4506" },
  { adTitle: "**Amazing 1 Bedroom Condo @Brickell w parking/pool", propertyId: "Club 2120" },
  { adTitle: "Amazing 1 Bedroom Condo @Brickell w parking/pool", propertyId: "Club 2120" },
  { adTitle: "1200 Brickell Bay Drive, Miami, Florida 33131, United States", propertyId: "Club 2120" },
  { adTitle: "Brickell Condo with Pool & Free Parking", propertyId: "Club 2120" },
  { adTitle: "Shuttle to Miami Stadium Games • 2BR •Pool/Gym", propertyId: "Club 2120" },
];
